Repository CommunityToolkit/Labs-Windows, pull requests merged in 2022-08, with the labels that each got.

#259 Update Testspace config based on recommendations from Testspace team
  .github/workflows/build.yml
Labels: testing 🏗, CI/pipeline 🔬

#264 Fixed Duplicate 'PackageDownload' errors in Release mode
  Windows.Toolkit.Common.props
Labels: build :fire:, nuget :package:

#260 GridSplitterControl
  labs/SizerBase/samples/SizerBase.Samples/GridSplitter.md
  labs/SizerBase/samples/SizerBase.Samples/GridSplitterPage.xaml
  labs/SizerBase/samples/SizerBase.Samples/GridSplitterPage.xaml.cs
Labels: sample app 🖼, controls :control_knobs:
