Repository CommunityToolkit/Labs-Windows, pull requests merged in 2022-12, with the labels that each got.

#335 De-duplicate our WinUI2/3 workflow definitions with a matrix
  .config/dotnet-tools.json
  .github/workflows/build.yml
Labels: enhancement, testing 🏗, build :fire:, CI/pipeline 🔬

#330 New <MultiTarget> system, added multitarget-aware ProjectReference generator
  .gitignore
  .vscode/launch.json
  DiscoverSamples.ps1
  GenerateAllSolution.ps1
  common/GenerateVSCodeLaunchConfig.ps1
  common/Labs.Head.props
  common/Labs.SampleRefs.props.template
  common/MultiTarget/Defaults.props
  common/MultiTarget/GenerateAllProjectReferences.ps1
  common/MultiTarget/GenerateMultiTargetAwareProjectReferenceProps.ps1
  common/MultiTarget/MultiTarget.props
  common/MultiTarget/MultiTargetAwareProjectReference.props.template
  common/MultiTarget/ReadMe.md
  common/SampleProjectConfig.props
  common/Scripts/UseUnoWinUI.ps1
  labs/CanvasLayout/samples/CanvasLayout.Samples/CanvasLayout.Samples.csproj
  labs/CanvasLayout/src/CommunityToolkit.Labs.WinUI.CanvasLayout.csproj
  labs/CanvasView/samples/CanvasView.Samples/CanvasView.Samples.csproj
  labs/CanvasView/src/CommunityToolkit.Labs.WinUI.CanvasView.csproj
  labs/RivePlayer/samples/RivePlayer.Samples/RivePlayer.Samples.csproj
  labs/RivePlayer/src/CommunityToolkit.Labs.WinUI.Rive.RivePlayer.csproj
  labs/RivePlayer/src/MultiTarget.props
  labs/SettingsControls/samples/SettingsControls.Samples/SettingsControls.Samples.csproj
  labs/SettingsControls/src/CommunityToolkit.Labs.WinUI.SettingsControls.csproj
  labs/SizerBase/samples/SizerBase.Samples/SizerBase.Samples.csproj
  labs/SizerBase/src/CommunityToolkit.Labs.WinUI.SizerBase.csproj
  labs/StackedNotificationsBehavior/samples/StackedNotificationsBehavior.Samples/StackedNotificationsBehavior.Samples.csproj
  labs/StackedNotificationsBehavior/src/CommunityToolkit.Labs.WinUI.StackedNotificationsBehavior.csproj
  labs/StackedNotificationsBehavior/src/MultiTarget.props
  platforms/CommunityToolkit.Labs.Droid/CommunityToolkit.Labs.Droid.csproj
  platforms/CommunityToolkit.Labs.Skia.Gtk/CommunityToolkit.Labs.Skia.Gtk.csproj
  platforms/CommunityToolkit.Labs.Skia.WPF/CommunityToolkit.Labs.Skia.WPF.csproj
  platforms/CommunityToolkit.Labs.Uwp/CommunityToolkit.Labs.Uwp.csproj
  platforms/CommunityToolkit.Labs.Wasm/CommunityToolkit.Labs.Wasm.csproj
  platforms/CommunityToolkit.Labs.WinAppSdk/CommunityToolkit.Labs.WinAppSdk.csproj
  platforms/CommunityToolkit.Labs.iOS/CommunityToolkit.Labs.iOS.csproj
  platforms/CommunityToolkit.Labs.macOS/CommunityToolkit.Labs.macOS.csproj
  template/lab/samples/ProjectTemplate.Samples/ProjectTemplate.Samples.csproj
  template/lab/src/CommunityToolkit.Labs.WinUI.ProjectTemplate.csproj
  template/lab/src/MultiTarget.props
  tests/CommunityToolkit.Labs.Tests.Uwp/CommunityToolkit.Labs.Tests.Uwp.csproj
  tests/CommunityToolkit.Labs.Tests.WinAppSdk/CommunityToolkit.Labs.Tests.WinAppSdk.csproj
Labels: dev loop ➰

#341 Updated workflow versions
  .config/dotnet-tools.json
  .github/workflows/build.yml
  common/Labs.Head.WinAppSdk.props
  common/MultiTarget/MultiTarget.props
  global.json
Labels: dev loop ➰, improvements :sparkles:
