Repository CommunityToolkit/Labs-Windows, pull requests merged in 2022-07, with the labels that each got.

#217 Updates to Readme
  CODE_OF_CONDUCT.md
  Contributing.md
  ReadMe.md
  common/ToolkitLabsSocial.png
Labels: documentation :page_with_curl:

#215 🧪 [Experiment] SettingsCard
  labs/SettingsControls/SettingsControls.sln
  labs/SettingsControls/samples/SettingsControls.Samples/Dependencies.props
  labs/SettingsControls/samples/SettingsControls.Samples/SettingsCardSample.xaml
  labs/SettingsControls/samples/SettingsControls.Samples/SettingsCardSample.xaml.cs
  labs/SettingsControls/samples/SettingsControls.Samples/SettingsControls.Samples.csproj
  labs/SettingsControls/samples/SettingsControls.Samples/SettingsControls.md
  labs/SettingsControls/samples/SettingsControls.Uwp/Package.appxmanifest
  labs/SettingsControls/samples/SettingsControls.Uwp/Properties/AssemblyInfo.cs
  labs/SettingsControls/samples/SettingsControls.Uwp/Properties/Default.rd.xml
  labs/SettingsControls/samples/SettingsControls.Uwp/SettingsControls.Uwp.csproj
  labs/SettingsControls/samples/SettingsControls.Wasm/Program.cs
  labs/SettingsControls/samples/SettingsControls.Wasm/Properties/launchSettings.json
  labs/SettingsControls/samples/SettingsControls.Wasm/SettingsControls.Wasm.csproj
  labs/SettingsControls/samples/SettingsControls.Wasm/WasmCSS/Fonts.css
  labs/SettingsControls/samples/SettingsControls.Wasm/WasmScripts/AppManifest.js
  labs/SettingsControls/samples/SettingsControls.Wasm/wwwroot/web.config
  labs/SettingsControls/samples/SettingsControls.WinAppSdk/Package.appxmanifest
  labs/SettingsControls/samples/SettingsControls.WinAppSdk/Properties/launchSettings.json
  labs/SettingsControls/samples/SettingsControls.WinAppSdk/SettingsControls.WinAppSdk.csproj
  labs/SettingsControls/samples/SettingsControls.WinAppSdk/app.manifest
  labs/SettingsControls/src/AdditionalAssemblyInfo.cs
  labs/SettingsControls/src/CommunityToolkit.Labs.WinUI.SettingsControls.csproj
  labs/SettingsControls/src/Dependencies.props
  labs/SettingsControls/src/SettingsCard/SettingsCard.Properties.cs
  labs/SettingsControls/src/SettingsCard/SettingsCard.cs
  labs/SettingsControls/src/SettingsCard/SettingsCard.xaml
  labs/SettingsControls/src/SettingsCard/SettingsCardAutomationPeer.cs
  labs/SettingsControls/src/SettingsCard/SettingsControls.cs
  labs/SettingsControls/src/Themes/Generic.xaml
  labs/SettingsControls/tests/SettingsControls.Tests.Uwp/Package.appxmanifest
  labs/SettingsControls/tests/SettingsControls.Tests.Uwp/Properties/AssemblyInfo.cs
  labs/SettingsControls/tests/SettingsControls.Tests.Uwp/Properties/Default.rd.xml
  labs/SettingsControls/tests/SettingsControls.Tests.Uwp/SettingsControls.Tests.Uwp.csproj
  labs/SettingsControls/tests/SettingsControls.Tests.WinAppSdk/Package.appxmanifest
  labs/SettingsControls/tests/SettingsControls.Tests.WinAppSdk/Properties/launchSettings.json
  labs/SettingsControls/tests/SettingsControls.Tests.WinAppSdk/SettingsControls.Tests.WinAppSdk.csproj
  labs/SettingsControls/tests/SettingsControls.Tests.WinAppSdk/app.manifest
  labs/SettingsControls/tests/SettingsControls.Tests/ExampleSettingsControlsTestClass.cs
  labs/SettingsControls/tests/SettingsControls.Tests/ExampleSettingsControlsTestPage.xaml
  labs/SettingsControls/tests/SettingsControls.Tests/ExampleSettingsControlsTestPage.xaml.cs
  labs/SettingsControls/tests/SettingsControls.Tests/SettingsControls.Tests.projitems
  labs/SettingsControls/tests/SettingsControls.Tests/SettingsControls.Tests.shproj
Labels: experiment :test_tube:

#214 🧪 Initial import of CanvasView Experiment
  labs/CanvasLayout/samples/CanvasLayout.Samples/CanvasLayout.md
  labs/CanvasView/CanvasView.sln
  labs/CanvasView/samples/CanvasView.Samples/CanvasView.Samples.csproj
  labs/CanvasView/samples/CanvasView.Samples/CanvasView.md
  labs/CanvasView/samples/CanvasView.Samples/CanvasViewDragSample.xaml
  labs/CanvasView/samples/CanvasView.Samples/CanvasViewDragSample.xaml.cs
  labs/CanvasView/samples/CanvasView.Samples/Dependencies.props
  labs/CanvasView/samples/CanvasView.Uwp/CanvasView.Uwp.csproj
  labs/CanvasView/samples/CanvasView.Uwp/Package.appxmanifest
  labs/CanvasView/samples/CanvasView.Uwp/Properties/AssemblyInfo.cs
  labs/CanvasView/samples/CanvasView.Uwp/Properties/Default.rd.xml
  labs/CanvasView/samples/CanvasView.Wasm/CanvasView.Wasm.csproj
  labs/CanvasView/samples/CanvasView.Wasm/Program.cs
  labs/CanvasView/samples/CanvasView.Wasm/Properties/launchSettings.json
  labs/CanvasView/samples/CanvasView.Wasm/WasmCSS/Fonts.css
  labs/CanvasView/samples/CanvasView.Wasm/WasmScripts/AppManifest.js
  labs/CanvasView/samples/CanvasView.Wasm/wwwroot/web.config
  labs/CanvasView/samples/CanvasView.WinAppSdk/CanvasView.WinAppSdk.csproj
  labs/CanvasView/samples/CanvasView.WinAppSdk/Package.appxmanifest
  labs/CanvasView/samples/CanvasView.WinAppSdk/Properties/launchSettings.json
  labs/CanvasView/samples/CanvasView.WinAppSdk/app.manifest
  labs/CanvasView/src/AdditionalAssemblyInfo.cs
  labs/CanvasView/src/CanvasView.cs
  labs/CanvasView/src/CommunityToolkit.Labs.WinUI.CanvasView.csproj
  labs/CanvasView/src/Dependencies.props
  labs/CanvasView/src/FrameworkElementExtensions.cs
  labs/CanvasView/tests/CanvasView.Tests.Uwp/CanvasView.Tests.Uwp.csproj
  labs/CanvasView/tests/CanvasView.Tests.Uwp/Package.appxmanifest
  labs/CanvasView/tests/CanvasView.Tests.Uwp/Properties/AssemblyInfo.cs
  labs/CanvasView/tests/CanvasView.Tests.Uwp/Properties/Default.rd.xml
  labs/CanvasView/tests/CanvasView.Tests.WinAppSdk/CanvasView.Tests.WinAppSdk.csproj
  labs/CanvasView/tests/CanvasView.Tests.WinAppSdk/Package.appxmanifest
  labs/CanvasView/tests/CanvasView.Tests.WinAppSdk/Properties/launchSettings.json
  labs/CanvasView/tests/CanvasView.Tests.WinAppSdk/app.manifest
  labs/CanvasView/tests/CanvasView.Tests/CanvasView.Tests.projitems
  labs/CanvasView/tests/CanvasView.Tests/CanvasView.Tests.shproj
  labs/CanvasView/tests/CanvasView.Tests/ExampleCanvasViewTestClass.cs
  labs/CanvasView/tests/CanvasView.Tests/ExampleCanvasViewTestPage.xaml
  labs/CanvasView/tests/CanvasView.Tests/ExampleCanvasViewTestPage.xaml.cs
  labs/SizerBase/samples/SizerBase.Samples/ContentSizer.md
  labs/SizerBase/samples/SizerBase.Samples/PropertySizer.md
  labs/SizerBase/samples/SizerBase.Samples/SizerControls.md
Labels: experiment :test_tube:

#209 Add GitHub Templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/experiment.yml
Labels: documentation :page_with_curl:

#226 Add missing rescaps as missed adding to template in #161
  labs/CanvasLayout/tests/CanvasLayout.Tests.Uwp/Package.appxmanifest
  labs/CanvasLayout/tests/CanvasLayout.Tests.WinAppSdk/Package.appxmanifest
  labs/CanvasView/tests/CanvasView.Tests.Uwp/Package.appxmanifest
  labs/CanvasView/tests/CanvasView.Tests.WinAppSdk/Package.appxmanifest
  labs/SettingsControls/tests/SettingsControls.Tests.Uwp/Package.appxmanifest
  labs/SettingsControls/tests/SettingsControls.Tests.WinAppSdk/Package.appxmanifest
  labs/SizerBase/tests/SizerBase.Tests.Uwp/Package.appxmanifest
  labs/SizerBase/tests/SizerBase.Tests.WinAppSdk/Package.appxmanifest
  template/lab/tests/ProjectTemplate.Tests.Uwp/Package.appxmanifest
  template/lab/tests/ProjectTemplate.Tests.WinAppSdk/Package.appxmanifest
Labels: testing 🏗, CI/pipeline 🔬, templating
