Repository CommunityToolkit/Labs-Windows, pull requests merged in 2023-03, with the labels that each got.

#380 Fixed building in codespaces
  .vscode/launch.json
  common/GenerateAllSolution.ps1
  common/GenerateVSCodeLaunchConfig.ps1
  common/MultiTarget/GenerateAllProjectReferences.ps1
  common/MultiTarget/GenerateMultiTargetAwareProjectReferenceProps.ps1
  common/MultiTarget/GetMultiTargets.ps1
  common/ProjectHeads/GenerateSingleSampleHeads.ps1
Labels: Uno, WASM, dev loop ➰

#374 [SegmentedControl] Adding AutoSelection and high contrast improvements
  components/SegmentedControl/samples/SegmentedControl.md
  components/SegmentedControl/samples/SegmentedControlBasicSample.xaml
  components/SegmentedControl/samples/SegmentedControlStylesSample.xaml
  components/SegmentedControl/samples/SegmentedControlStylesSample.xaml.cs
  components/SegmentedControl/src/EqualPanel.cs
  components/SegmentedControl/src/Helpers/SegmentedMarginConverter.cs
  components/SegmentedControl/src/Segmented/Segmented.cs
  components/SegmentedControl/src/Segmented/Segmented.xaml
  components/SegmentedControl/src/SegmentedItem/SegmentedItem.Properties.cs
  components/SegmentedControl/src/SegmentedItem/SegmentedItem.cs
  components/SegmentedControl/src/SegmentedItem/SegmentedItem.xaml
Labels: experiment :test_tube:

#396 [Gallery] Fix for WASDK titlebar brush
  common/CommunityToolkit.App.Shared/App.xaml
Labels: sample app 🖼

#391 [Experiment] Shimmer
  components/Shimmer/OpenSolution.bat
  components/Shimmer/samples/Assets/Owl.jpg
  components/Shimmer/samples/Dependencies.props
  components/Shimmer/samples/MultiTarget.props
  components/Shimmer/samples/Shimmer.Samples.csproj
  components/Shimmer/samples/Shimmer.md
  components/Shimmer/samples/ShimmerSample.xaml
  components/Shimmer/samples/ShimmerSample.xaml.cs
  components/Shimmer/src/AdditionalAssemblyInfo.cs
  components/Shimmer/src/CommunityToolkit.Labs.WinUI.Shimmer.csproj
  components/Shimmer/src/Dependencies.props
  components/Shimmer/src/MultiTarget.props
  components/Shimmer/src/Shimmer/Shimmer.Properties.cs
  components/Shimmer/src/Shimmer/Shimmer.cs
  components/Shimmer/src/Shimmer/Shimmer.xaml
  components/Shimmer/src/Themes/Generic.xaml
  components/Shimmer/tests/ExampleShimmerTestClass.cs
  components/Shimmer/tests/ExampleShimmerTestPage.xaml
  components/Shimmer/tests/ExampleShimmerTestPage.xaml.cs
  components/Shimmer/tests/Shimmer.Tests.projitems
  components/Shimmer/tests/Shimmer.Tests.shproj
Labels: experiment :test_tube:

#400 Remove package ID from Segmented/Shimmer
  components/SegmentedControl/src/CommunityToolkit.Labs.WinUI.SegmentedControl.csproj
  components/Shimmer/src/CommunityToolkit.Labs.WinUI.Shimmer.csproj
  template/ProjectTemplate/src/CommunityToolkit.Labs.WinUI.ProjectTemplate.csproj
Labels: build :fire:, templating

#394 Updated the default namespace for new components
  Directory.Build.props
  common/GlobalUsings_WinUI.cs
  common/ToolkitComponent.SourceProject.props
  components/CanvasLayout/samples/CanvasLayoutSample.xaml.cs
  components/CanvasLayout/tests/ExampleCanvasLayoutTestClass.cs
  components/CanvasView/tests/ExampleCanvasViewTestClass.cs
  components/SegmentedControl/samples/SegmentedControlBasicSample.xaml.cs
  components/SegmentedControl/tests/ExampleSegmentedControlTestClass.cs
  components/SettingsControls/tests/ExampleSettingsControlsTestClass.cs
  components/Shimmer/tests/ExampleShimmerTestClass.cs
  components/SizerBase/tests/ExampleSizerBaseTestClass.cs
  components/StackedNotificationsBehavior/samples/StackedNotificationsBehaviorCustomSample.xaml.cs
  components/StackedNotificationsBehavior/tests/ExampleStackedNotificationsBehaviorTestClass.cs
  template/ProjectTemplate/samples/ProjectTemplateCustomSample.xaml
  template/ProjectTemplate/samples/ProjectTemplateCustomSample.xaml.cs
  template/ProjectTemplate/samples/ProjectTemplateTemplatedSample.xaml
  template/ProjectTemplate/samples/ProjectTemplateTemplatedStyleCustomSample.xaml
  template/ProjectTemplate/samples/ProjectTemplateXbindBackedSample.xaml
  template/ProjectTemplate/samples/ProjectTemplateXbindBackedStyleCustomSample.xaml
  template/ProjectTemplate/src/CommunityToolkit.WinUI.Controls.ProjectTemplate.csproj
  template/ProjectTemplate/src/ProjectTemplate.cs
  template/ProjectTemplate/src/ProjectTemplateStyle_ClassicBinding.xaml
  template/ProjectTemplate/src/ProjectTemplateStyle_xBind.xaml
  template/ProjectTemplate/src/ProjectTemplateStyle_xBind.xaml.cs
  template/ProjectTemplate/src/ProjectTemplate_ClassicBinding.cs
  template/ProjectTemplate/src/ProjectTemplate_xBind.cs
  template/ProjectTemplate/src/Themes/Generic.xaml
  template/ProjectTemplate/tests/ExampleProjectTemplateTestClass.cs
  template/ProjectTemplate/tests/ExampleProjectTemplateTestPage.xaml
  template/README.md
Labels: enhancement, dev loop ➰

#403 Move project template from /template/ProjectTemplate to /common/ProjectTemplate
  .github/workflows/build.yml
  ReadMe.md
  common/CommunityToolkit.Tooling.SampleGen/ToolkitSampleMetadataGenerator.Documentation.cs
  common/ProjectTemplate/.template.config/ide.host.json
  common/ProjectTemplate/.template.config/template.json
  common/ProjectTemplate/OpenSolution.bat
  common/ProjectTemplate/README.md
  common/ProjectTemplate/samples/Dependencies.props
  common/ProjectTemplate/samples/ProjectTemplate.Samples.csproj
  common/ProjectTemplate/samples/ProjectTemplate.md
  common/ProjectTemplate/samples/ProjectTemplateCustomSample.xaml
  common/ProjectTemplate/samples/ProjectTemplateCustomSample.xaml.cs
  common/ProjectTemplate/samples/ProjectTemplateTemplatedSample.xaml
  common/ProjectTemplate/samples/ProjectTemplateTemplatedSample.xaml.cs
  common/ProjectTemplate/samples/ProjectTemplateTemplatedStyleCustomSample.xaml
  common/ProjectTemplate/samples/ProjectTemplateTemplatedStyleCustomSample.xaml.cs
  common/ProjectTemplate/samples/ProjectTemplateXbindBackedSample.xaml
  common/ProjectTemplate/samples/ProjectTemplateXbindBackedSample.xaml.cs
  common/ProjectTemplate/samples/ProjectTemplateXbindBackedStyleCustomSample.xaml
  common/ProjectTemplate/samples/ProjectTemplateXbindBackedStyleCustomSample.xaml.cs
  common/ProjectTemplate/src/AdditionalAssemblyInfo.cs
  common/ProjectTemplate/src/CommunityToolkit.WinUI.Controls.ProjectTemplate.csproj
  common/ProjectTemplate/src/Dependencies.props
  common/ProjectTemplate/src/MultiTarget.props
  common/ProjectTemplate/src/ProjectTemplate.cs
  common/ProjectTemplate/src/ProjectTemplateStyle_ClassicBinding.xaml
  common/ProjectTemplate/src/ProjectTemplateStyle_xBind.xaml
  common/ProjectTemplate/src/ProjectTemplateStyle_xBind.xaml.cs
  common/ProjectTemplate/src/ProjectTemplate_ClassicBinding.cs
  common/ProjectTemplate/src/ProjectTemplate_xBind.cs
  common/ProjectTemplate/src/Themes/Generic.xaml
  common/ProjectTemplate/tests/ExampleProjectTemplateTestClass.cs
  common/ProjectTemplate/tests/ExampleProjectTemplateTestPage.xaml
  common/ProjectTemplate/tests/ExampleProjectTemplateTestPage.xaml.cs
  common/ProjectTemplate/tests/ProjectTemplate.Tests.projitems
  common/ProjectTemplate/tests/ProjectTemplate.Tests.shproj
Labels: CI/pipeline 🔬, templating

#410 Fixed SettingsCard not lost force when touch leave
  components/SettingsControls/src/SettingsCard/SettingsCard.cs
Labels: experiment :test_tube:, issue 🧪

#348 🧪 [Experiment] TokenView
  components/TokenView/OpenSolution.bat
  components/TokenView/samples/Dependencies.props
  components/TokenView/samples/TokenView.Samples.csproj
  components/TokenView/samples/TokenView.md
  components/TokenView/samples/TokenViewBasicSample.xaml
  components/TokenView/samples/TokenViewBasicSample.xaml.cs
  components/TokenView/samples/TokenViewItemsSourceSample.xaml
  components/TokenView/samples/TokenViewItemsSourceSample.xaml.cs
  components/TokenView/samples/TokenViewRemoveSample.cs
  components/TokenView/samples/TokenViewRemoveSample.xaml
  components/TokenView/src/AdditionalAssemblyInfo.cs
  components/TokenView/src/CommunityToolkit.Labs.WinUI.TokenView.csproj
  components/TokenView/src/Dependencies.props
  components/TokenView/src/Helpers/ControlHelpers.cs
  components/TokenView/src/Helpers/WrapPanel.cs
  components/TokenView/src/Themes/Generic.xaml
  components/TokenView/src/TokenItem/TokenItem.Properties.cs
  components/TokenView/src/TokenItem/TokenItem.cs
  components/TokenView/src/TokenItem/TokenItem.xaml
  components/TokenView/src/TokenItem/TokenItemRemovingEventArgs.cs
  components/TokenView/src/TokenView/TokenView.Events.cs
  components/TokenView/src/TokenView/TokenView.ItemsSource.cs
  components/TokenView/src/TokenView/TokenView.Properties.cs
  components/TokenView/src/TokenView/TokenView.Selection.cs
  components/TokenView/src/TokenView/TokenView.cs
  components/TokenView/src/TokenView/TokenView.xaml
  components/TokenView/tests/ExampleTokenViewTestClass.cs
  components/TokenView/tests/ExampleTokenViewTestPage.xaml
  components/TokenView/tests/ExampleTokenViewTestPage.xaml.cs
  components/TokenView/tests/TokenView.Tests.projitems
  components/TokenView/tests/TokenView.Tests.shproj
Labels: experiment :test_tube:
